import { RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';
import { HomeComponent } from './components/home/home.component';
import { SetupComponent } from './components/setup/setup.component';
import { ShowcaseComponent } from './showcase.component';


const showCaseRoutes: Routes = [
    {path:'', 
    component:ShowcaseComponent,
    data: {breadcrumb: null},
    children : [
    {path: '', component: SetupComponent, data: {breadcrumb: 'setup'}},
    {path: 'setup', loadChildren: () => import('./components/setup/setup.module').then(m => m.SetupModule),data: {breadcrumb: 'setup'}},
    {path: 'theming', loadChildren: () => import('./components/theming/theming.module').then(m => m.ThemingModule),data: {breadcrumb: 'theming'}},
    {path: 'icons', loadChildren: () => import('./components/icons/icons.module').then(m => m.IconsModule),data: {breadcrumb: 'icons'}},
    {path: 'accordion', loadChildren: () => import('./components/accordion/accordiondemo.module').then(m => m.AccordionDemoModule),data: {breadcrumb: 'accordion'}},
    {path: 'autocomplete', loadChildren: () => import('./components/autocomplete/autocompletedemo.module').then(m => m.AutoCompleteDemoModule), data: {breadcrumb: 'autocomplete'}},
    {path: 'blockui', loadChildren: () => import('./components/blockui/blockuidemo.module').then(m => m.BlockUIDemoModule),data: {breadcrumb: 'blockui'}},
    {path: 'breadcrumb', loadChildren: () => import('./components/breadcrumb/breadcrumbdemo.module').then(m => m.BreadcrumbDemoModule), data: {breadcrumb: 'breadcrumb'}},
    {path: 'button', loadChildren: () => import('./components/button/buttondemo.module').then(m => m.ButtonDemoModule), data: {breadcrumb: 'button'}},
    {path: 'calendar', loadChildren: () => import('./components/calendar/calendardemo.module').then(m => m.CalendarDemoModule), data: {breadcrumb: 'calendar'}},
    {path: 'captcha', loadChildren: () => import('./components/captcha/captchademo.module').then(m => m.CaptchaDemoModule),data: {breadcrumb: 'captcha'}},
    {path: 'card', loadChildren: () => import('./components/card/carddemo.module').then(m => m.CardDemoModule), data: {breadcrumb: 'card'}},
    {path: 'carousel', loadChildren: () => import('./components/carousel/carouseldemo.module').then(m => m.CarouselDemoModule), data: {breadcrumb: 'carousel'}},
    {path: 'chart', loadChildren: () => import('./components/chart/chartdemo.module').then(m => m.ChartDemoModule),data: {breadcrumb: 'chart'}},
    {path: 'checkbox', loadChildren: () => import('./components/checkbox/checkboxdemo.module').then(m => m.CheckboxDemoModule), data: {breadcrumb: 'checkbox'}},
    {path: 'chips', loadChildren: () => import('./components/chips/chipsdemo.module').then(m => m.ChipsDemoModule),data: {breadcrumb: 'chips'}},
    {path: 'codehighlighter', loadChildren: () => import('./components/codehighlighter/codehighlighterdemo.module').then(m => m.CodeHighlighterDemoModule),data: {breadcrumb: 'codehighlighter'}},
    {path: 'colorpicker', loadChildren: () => import('./components/colorpicker/colorpickerdemo.module').then(m => m.ColorPickerDemoModule),data: {breadcrumb: 'colorpicker'}},
    {path: 'confirmdialog', loadChildren: () => import('./components/confirmdialog/confirmdialogdemo.module').then(m => m.ConfirmDialogDemoModule),data: {breadcrumb: 'confirmdialog'}},
    {path: 'contextmenu', loadChildren: () => import('./components/contextmenu/contextmenudemo.module').then(m => m.ContextMenuDemoModule),data: {breadcrumb: 'contextmenu'}},
    {path: 'dataview', loadChildren: () => import('./components/dataview/dataviewdemo.module').then(m => m.DataViewDemoModule), data: {breadcrumb: 'dataview'}},
    {path: 'defer', loadChildren: () => import('./components/defer/deferdemo.module').then(m => m.DeferDemoModule),data: {breadcrumb: 'defer'}},
    {path: 'dialog', loadChildren: () => import('./components/dialog/dialogdemo.module').then(m => m.DialogDemoModule), data: {breadcrumb: 'dialog'}},
    {path: 'dynamicdialog', loadChildren: () => import('./components/dynamicdialog/dynamicdialogdemo.module').then(m => m.DynamicDialogDemoModule),data: {breadcrumb: 'dynamicdialog'}},
    {path: 'dragdrop', loadChildren: () => import('./components/dragdrop/dragdropdemo.module').then(m => m.DragDropDemoModule), data: {breadcrumb: 'dragdrop'}},
    {path: 'dropdown', loadChildren: () => import('./components/dropdown/dropdowndemo.module').then(m => m.DropdownDemoModule), data: {breadcrumb: 'dropdown'}},
    {path: 'editor', loadChildren: () => import('./components/editor/editordemo.module').then(m => m.EditorDemoModule), data: {breadcrumb: 'editor'}},
    {path: 'fieldset', loadChildren: () => import('./components/fieldset/fieldsetdemo.module').then(m => m.FieldsetDemoModule), data: {breadcrumb: 'fieldset'}},
    {path: 'fileupload', loadChildren: () => import('./components/fileupload/fileuploaddemo.module').then(m => m.FileUploadDemoModule), data: {breadcrumb: 'fileupload'}},
    {path: 'filterutils', loadChildren: () => import('./components/filterutils/filterutilsdemo.module').then(m => m.FilterUtilsDemoModule),data: {breadcrumb: 'filterutils'}},
    {path: 'flexgrid', loadChildren: () => import('./components/flexgrid/flexgriddemo.module').then(m => m.FlexGridDemoModule), data: {breadcrumb: 'flexgrid'}},
    {path: 'focustrap', loadChildren: () => import('./components/focustrap/focustrapdemo.module').then(m => m.FocusTrapDemoModule),data: {breadcrumb: 'focustrap'}},
    {path: 'fullcalendar', loadChildren: () => import('./components/fullcalendar/fullcalendardemo.module').then(m => m.FullCalendarDemoModule), data: {breadcrumb: 'fullcalendar'}},
    {path: 'galleria', loadChildren: () => import('./components/galleria/galleriademo.module').then(m => m.GalleriaDemoModule), data: {breadcrumb: 'galleria'}},
    {path: 'gmap', loadChildren: () => import('./components/gmap/gmapdemo.module').then(m => m.GMapDemoModule), data: {breadcrumb: 'gmap'}},
    {path: 'inplace', loadChildren: () => import('./components/inplace/inplacedemo.module').then(m => m.InplaceDemoModule),data: {breadcrumb: 'inplace'}},
    {path: 'inputmask', loadChildren: () => import('./components/inputmask/inputmaskdemo.module').then(m => m.InputMaskDemoModule),data: {breadcrumb: 'inputmask'}},
    {path: 'inputswitch', loadChildren: () => import('./components/inputswitch/inputswitchdemo.module').then(m => m.InputSwitchDemoModule),data: {breadcrumb: 'inputswitch'}},
    {path: 'inputtext', loadChildren: () => import('./components/inputtext/inputtextdemo.module').then(m => m.InputTextDemoModule),data: {breadcrumb: 'inputtext'}},
    {path: 'inputgroup', loadChildren: () => import('./components/inputgroup/inputgroupdemo.module').then(m => m.InputGroupDemoModule), data: {breadcrumb: 'inputgroup'}},
    {path: 'inputtextarea', loadChildren: () => import('./components/inputtextarea/inputtextareademo.module').then(m => m.InputTextareaDemoModule),data: {breadcrumb: 'inputtextarea'}},
    {path: 'keyfilter', loadChildren: () => import('./components/keyfilter/keyfilterdemo.module').then(m => m.KeyFilterDemoModule),data: {breadcrumb: 'keyfilter'}},
    {path: 'lightbox', loadChildren: () => import('./components/lightbox/lightboxdemo.module').then(m => m.LightboxDemoModule), data: {breadcrumb: 'lightbox'}},
    {path: 'listbox', loadChildren: () => import('./components/listbox/listboxdemo.module').then(m => m.ListboxDemoModule),data: {breadcrumb: 'listbox'}},
    {path: 'lts', loadChildren: () => import('./components/lts/lts.module').then(m => m.LTSModule),data: {breadcrumb: 'lts'}},
    {path: 'megamenu', loadChildren: () => import('./components/megamenu/megamenudemo.module').then(m => m.MegaMenuDemoModule), data: {breadcrumb: 'megamenu'}},
    {path: 'menu', loadChildren: () => import('./components/menu/menudemo.module').then(m => m.MenuDemoModule), data: {breadcrumb: 'menu'}},
    {path: 'menubar', loadChildren: () => import('./components/menubar/menubardemo.module').then(m => m.MenubarDemoModule),data: {breadcrumb: 'menubar'}},
    {path: 'menumodel', loadChildren: () => import('./components/menumodel/menumodeldemo.module').then(m => m.MenuModelDemoModule),data: {breadcrumb: 'menumodel'}},
    {path: 'messages', loadChildren: () => import('./components/messages/messagesdemo.module').then(m => m.MessagesDemoModule), data: {breadcrumb: 'messages'}},
    {path: 'multiselect', loadChildren: () => import('./components/multiselect/multiselectdemo.module').then(m => m.MultiSelectDemoModule),data: {breadcrumb: 'multiselect'}},
    {path: 'orderlist', loadChildren: () => import('./components/orderlist/orderlistdemo.module').then(m => m.OrderListDemoModule),data: {breadcrumb: 'orderlist'}},
    {path: 'organizationchart', loadChildren: () => import('./components/organizationchart/organizationchartdemo.module').then(m => m.OrganizationChartDemoModule),data: {breadcrumb: 'organizationchart'}},
    {path: 'overlaypanel', loadChildren: () => import('./components/overlaypanel/overlaypaneldemo.module').then(m => m.OverlayPanelDemoModule), data: {breadcrumb: 'overlaypanel'}},
    {path: 'paginator', loadChildren: () => import('./components/paginator/paginatordemo.module').then(m => m.PaginatorDemoModule),data: {breadcrumb: 'paginator'}},
    {path: 'panel', loadChildren: () => import('./components/panel/paneldemo.module').then(m => m.PanelDemoModule),data: {breadcrumb: 'panel'}},
    {path: 'panelmenu', loadChildren: () => import('./components/panelmenu/panelmenudemo.module').then(m => m.PanelMenuDemoModule),data: {breadcrumb: 'panelmenu'}},
    {path: 'password', loadChildren: () => import('./components/password/passworddemo.module').then(m => m.PasswordDemoModule), data: {breadcrumb: 'password'}},
    {path: 'picklist', loadChildren: () => import('./components/picklist/picklistdemo.module').then(m => m.PickListDemoModule), data: {breadcrumb: 'picklist'}},
    {path: 'progressbar', loadChildren: () => import('./components/progressbar/progressbardemo.module').then(m => m.ProgressBarDemoModule),data: {breadcrumb: 'progressbar'}},
    {path: 'progressspinner', loadChildren: () => import('./components/progressspinner/progressspinnerdemo.module').then(m => m.ProgressSpinnerDemoModule),data: {breadcrumb: 'progressspinner'}},
    {path: 'radiobutton', loadChildren: () => import('./components/radiobutton/radiobuttondemo.module').then(m => m.RadioButtonDemoModule),data: {breadcrumb: 'radiobutton'}},
    {path: 'rating', loadChildren: () => import('./components/rating/ratingdemo.module').then(m => m.RatingDemoModule), data: {breadcrumb: 'rating'}},
    {path: 'responsive', loadChildren: () => import('./components/responsive/responsivedemo.module').then(m => m.ResponsiveDemoModule), data: {breadcrumb: 'responsive'}},
    {path: 'rtl', loadChildren: () => import('./components/rtl/rtldemo.module').then(m => m.RTLDemoModule),data: {breadcrumb: 'rtl'}},
    {path: 'scrollpanel', loadChildren: () => import('./components/scrollpanel/scrollpaneldemo.module').then(m => m.ScrollPanelDemoModule) , data: {breadcrumb: 'scrollpanel'}},
    {path: 'selectbutton', loadChildren: () => import('./components/selectbutton/selectbuttondemo.module').then(m => m.SelectButtonDemoModule), data: {breadcrumb: 'selectbutton'}},
    {path: 'sidebar', loadChildren: () => import('./components/sidebar/sidebardemo.module').then(m => m.SidebarDemoModule),data: {breadcrumb: 'sidebar'}},
    {path: 'slidemenu', loadChildren: () => import('./components/slidemenu/slidemenudemo.module').then(m => m.SlideMenuDemoModule),data: {breadcrumb: 'slidemenu'}},
    {path: 'slider', loadChildren: () => import('./components/slider/sliderdemo.module').then(m => m.SliderDemoModule), data: {breadcrumb: 'slider'}},
    {path: 'spinner', loadChildren: () => import('./components/spinner/spinnerdemo.module').then(m => m.SpinnerDemoModule),data: {breadcrumb: 'spinner'}},
    {path: 'splitbutton', loadChildren: () => import('./components/splitbutton/splitbuttondemo.module').then(m => m.SplitButtonDemoModule),data: {breadcrumb: 'splitbutton'}},
    {path: 'steps', loadChildren: () => import('./components/steps/stepsdemo.module').then(m => m.StepsDemoModule),data: {breadcrumb: 'steps'}},
    {path: 'support', loadChildren: () => import('./components/support/support.module').then(m => m.SupportModule),data: {breadcrumb: 'support'}},
    {path: 'table', loadChildren: () => import('./components/table/tabledemo.module').then(m => m.TableDemoModule),data: {breadcrumb: 'table'}},
    {path: 'tabmenu', loadChildren: () => import('./components/tabmenu/tabmenudemo.module').then(m => m.TabMenuDemoModule),data: {breadcrumb: 'tabmenu'}},
    {path: 'tabview', loadChildren: () => import('./components/tabview/tabviewdemo.module').then(m => m.TabViewDemoModule),data: {breadcrumb: 'tabview'}},
    {path: 'terminal', loadChildren: () => import('./components/terminal/terminaldemo.module').then(m => m.TerminalDemoModule), data: {breadcrumb: 'terminal'}},
    {path: 'tieredmenu', loadChildren: () => import('./components/tieredmenu/tieredmenudemo.module').then(m => m.TieredMenuDemoModule), data: {breadcrumb: 'tieredmenu'}},
    {path: 'toast', loadChildren: () => import('./components/toast/toastdemo.module').then(m => m.ToastDemoModule),data: {breadcrumb: 'toast'}},
    {path: 'togglebutton', loadChildren: () => import('./components/togglebutton/togglebuttondemo.module').then(m => m.ToggleButtonDemoModule), data: {breadcrumb: 'togglebutton'}},
    {path: 'toolbar', loadChildren: () => import('./components/toolbar/toolbardemo.module').then(m => m.ToolbarDemoModule),data: {breadcrumb: 'toolbar'}},
    {path: 'tooltip', loadChildren: () => import('./components/tooltip/tooltipdemo.module').then(m => m.TooltipDemoModule),data: {breadcrumb: 'tooltip'}},
    {path: 'tree', loadChildren: () => import('./components/tree/treedemo.module').then(m => m.TreeDemoModule), data: {breadcrumb: 'tree'}},
    {path: 'treetable', loadChildren: () => import('./components/treetable/treetabledemo.module').then(m => m.TreeTableDemoModule),data: {breadcrumb: 'treetable'}},
    {path: 'tristatecheckbox', loadChildren: () => import('./components/tristatecheckbox/tristatecheckboxdemo.module').then(m => m.TriStateCheckboxDemoModule), data: {breadcrumb: 'tristatecheckbox'}},
    {path: 'validation', loadChildren: () => import('./components/validation/validationdemo.module').then(m => m.ValidationDemoModule), data: {breadcrumb: 'validation'}},
    {path: 'virtualscroller', loadChildren: () => import('./components/virtualscroller/virtualscrollerdemo.module').then(m => m.VirtualScrollerDemoModule),data: {breadcrumb: 'virtualscroller'}},
  ]}
  ];
  
  @NgModule({
    imports: [
      RouterModule.forChild(showCaseRoutes)
    ],
    exports: [
      RouterModule
    ]
  })
  export class ShowcaseRoutingModule { }